services:
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - ".env"
    networks:
      - app_network

  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio_api_drf_web
    ports:
      - "8000:8000"
    volumes:
      - .:/app
      - static_volume:/staticfiles  # Static fayllarni ushbu volume orqali ulash
      - media_volume:/media
    depends_on:
      - db
    env_file:
      - ".env"
    networks:
      - app_network
    command: ["sh", "-c", "python manage.py collectstatic --noinput && gunicorn portfolio_api_drf_web.wsgi:application --bind 0.0.0.0:8000"]

  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: portfolio_api_drf_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/staticfiles  # Static fayllarni bu yerga ulash
      - media_volume:/media
    depends_on:
      - web
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data:
  static_volume:
  media_volume:
